backend:
  name: git-gateway
  repo: CodeInvers3/codeinvers3.github.io
  branch: master
media_folder: "images"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    filter:
      field: language
      value: en
    fields:
      - { label: "Language", name: "language" }
