name: Crear nuevo post
on:
  push:
    branches: [ master ]
jobs:
  crear-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install
      - run: node addpost.js